import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const thamaniah = localFont({
  src: "../fonts/thmanyahsans-Regular.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ali Alshehri",
  description: "Generated by wm0x",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${thamaniah.className} antialiased [font-feature-settings:'salt'_1]`}
      >
        {children}
      </body>
    </html>
  );
}
